name: Moobeside CI

on:
  pull_request:
    # feature/foo, feature/foo/bar/* 까지 대응
    branches: [ "feature/**", "hotfix/**", "release/**", "develop", "main" ]

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: cache gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: jdk 17 setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Restore jks and keystore properties
        run: |
          mkdir -p ./keystore
          
          echo "${{ secrets.DEV_JKS_BASE64 }}" | base64 -d > ./keystore/dev.jks
          echo "${{ secrets.PROD_JKS_BASE64 }}" | base64 -d > ./keystore/prod.jks
          
          echo "storeFileDev=./keystore/dev.jks" > keystore.properties
          echo "storeFileProd=./keystore/prod.jks" >> keystore.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Generate local.properties
        run: |
          echo KOBIS_API_KEY=\"$KOBIS_API_KEY\" >> local.properties
          echo TMDB_API_KEY=\"$TMDB_API_KEY\" >> local.properties
          echo YOUTUBE_API_KEY=\"$YOUTUBE_API_KEY\" >> local.properties
        shell: bash
        env:
          KOBIS_API_KEY: ${{ secrets.KOBIS_API_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      #      - name: Set google-services.json
      #        run:
      #          echo "${{ secrets.GOOGLE_SERVICE_JSON }}" > ./app/google-services.json

      - name: Build with Gradle
        run: ./gradlew assembleDebug
